apiVersion: v1
kind: Service
metadata:
  name: jellyfin-discovery
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
  annotations:
    lbipam.cilium.io/ips: "10.1.1.61"
    lbipam.cilium.io/sharing-key: db3000
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: discovery
      port: 7359
      targetPort: 7359
      protocol: UDP
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
