media-app:
  image:
    repository: ghcr.io/linuxserver/radarr
    tag: "6.1.1"
  containerPort: 7878
  env:
    TZ: Europe/London
    PUID: "568"
    PGID: "1001"
    UMASK: "007"
  persistence:
    config:
      size: 2Gi
      existingVolume: db3000-radarr-config
    media:
      enabled: true
  httproute:
    path: /radarr
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi
