argo-cd:
  global:
    domain: argocd.xmple.io

  repoServer:
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 5
      periodSeconds: 30
      timeoutSeconds: 5

  server:
    insecure: true

  configs:
    params:
      server.insecure: true

    cm:
      url: https://argocd.xmple.io
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
                - name: xmple

    rbac:
      policy.default: role:admin
      scopes: "[groups]"
