argo-cd:
  server:
    insecure: true

  configs:
    params:
      server.insecure: true
    repositories:
      talos-cluster:
        url: git@github.com:xmple/talos-cluster.git
        type: git
        sshPrivateKeySecret:
          name: argocd-repo-key
          key: sshPrivateKey
