apiVersion: v1
kind: Service
metadata:
  name: transmission-bittorrent
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
  annotations:
    lbipam.cilium.io/ips: "10.1.1.53"
    lbipam.cilium.io/sharing-key: db3000
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: bittorrent-tcp
      port: 51413
      targetPort: 51413
      protocol: TCP
    - name: bittorrent-udp
      port: 51413
      targetPort: 51413
      protocol: UDP
  selector:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: {{ .Release.Name }}
