apiVersion: v1
kind: Service
metadata:
  name: transmission-vpn
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 8888
      targetPort: proxy
      protocol: TCP
  selector:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: {{ .Release.Name }}
