apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg-cluster
spec:
  instances: 3

  storage:
    size: 10Gi
    storageClass: longhorn-single-replica

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi

  affinity:
    topologyKey: kubernetes.io/hostname

  enableSuperuserAccess: true
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised

  bootstrap:
    recovery:
      source: cnpg-cluster-backup
${RECOVERY_TARGET}
  externalClusters:
    - name: cnpg-cluster-backup
      barmanObjectStore:
        endpointURL: "https://s3.xmple.io:9000"
        destinationPath: "s3://cnpg-backup/"
        s3Credentials:
          accessKeyId:
            name: cnpg-s3-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: cnpg-s3-creds
            key: ACCESS_SECRET_KEY
        wal:
          compression: gzip
          maxParallel: 1
