apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
  annotations:
    lbipam.cilium.io/ips: "10.1.1.61"
    lbipam.cilium.io/sharing-key: db3000
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
      protocol: TCP
  selector:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
