apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "recyclarr.labels" . | nindent 4 }}
data:
  recyclarr.yml: |
    {{- .Values.config | nindent 4 }}
