minecraft-server:
  port: 19132
  env:
    EULA: "true"
    TZ: Europe/London
    VERSION: LATEST
    EMIT_SERVER_TELEMETRY: "true"
    ENABLE_LAN_VISIBILITY: "true"
    PACKAGE_BACKUP_KEEP: "2"
    VIEW_DISTANCE: "32"
    SERVER_NAME: Deddy
    GAMEMODE: creative
    DIFFICULTY: easy
    LEVEL_NAME: My World
    LEVEL_SEED: "7794572526148668328"
    LEVEL_TYPE: DEFAULT
    OPS: "2533274949710273"
    ALLOW_LIST: "true"
    ALLOW_LIST_USERS: "Deddy:2533274949710273,Luna:2535463308445170"
    SERVER_PORT: "19132"
