minecraft-server:
  persistence:
    existingVolume: minecraft-server-mc1
  env:
    SERVER_NAME: Deddy
    GAMEMODE: creative
    DIFFICULTY: easy
    LEVEL_NAME: My World
    LEVEL_SEED: "7794572526148668328"
    LEVEL_TYPE: DEFAULT
    OPS: "2533274949710273"
    ALLOW_LIST: "true"
    ALLOW_LIST_USERS: "Deddy:2533274949710273,Luna:2535463308445170"
