apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-media-share
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0770
    - file_mode=0660
    - uid=568
    - gid=1001
    - forceuid
    - forcegid
    - mfsymlinks
    - nobrl
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: db3000-media-share
    volumeAttributes:
      source: "//10.1.1.30/Media"
    nodeStageSecretRef:
      name: media-smb-creds
      namespace: db3000
