media-app:
  image:
    repository: ghcr.io/jellyfin/jellyfin
  containerPort: 8096
  env:
    JELLYFIN_PublishedServerUrl: https://db3000.xmple.io/jellyfin
    JELLYFIN_hostwebclient: "true"
  persistence:
    config:
      size: 10Gi
      existingVolume: db3000-jellyfin-config
    media:
      enabled: true
  nodeSelector:
    gpu.intel.com/device-id.0300-3e92.present: "true"
  extraVolumes:
    - name: cache
      persistentVolumeClaim:
        claimName: jellyfin-cache
  extraVolumeMounts:
    - name: cache
      mountPath: /cache
  httproute:
    path: /jellyfin
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
      gpu.intel.com/i915: "1"
