media-app:
  image:
    repository: ghcr.io/jellyfin/jellyfin
  containerPort: 8096
  env:
    JELLYFIN_PublishedServerUrl: https://db3000.xmple.io/jellyfin
    JELLYFIN_hostwebclient: "true"
  persistence:
    config:
      size: 10Gi
      existingVolume: db3000-jellyfin-config
    media:
      enabled: true
  securityContext:
    privileged: true
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
  extraVolumes:
    - name: cache
      persistentVolumeClaim:
        claimName: jellyfin-cache
    - name: dri
      hostPath:
        path: /dev/dri
        type: Directory
  extraVolumeMounts:
    - name: cache
      mountPath: /cache
    - name: dri
      mountPath: /dev/dri
  httproute:
    path: /jellyfin
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
