apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - start: 10.1.1.60
      stop: 10.1.1.60
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: db3000-pool
spec:
  blocks:
    - start: 10.1.1.61
      stop: 10.1.1.61
  serviceSelector:
    matchLabels:
      app.kubernetes.io/part-of: db3000
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: gitea-pool
spec:
  blocks:
    - start: 10.1.1.62
      stop: 10.1.1.62
  serviceSelector:
    matchLabels:
      app.kubernetes.io/part-of: gitea
