traefik:
  providers:
    kubernetesGateway:
      enabled: true
      experimentalChannel: true
    kubernetesIngress:
      enabled: false

  gateway:
    enabled: false

  ports:
    gitea-ssh:
      port: 2222
      expose:
        default: true
      exposedPort: 22
      protocol: TCP

  deployment:
    replicas: 2

  service:
    annotations:
      lbipam.cilium.io/sharing-key: default
      lbipam.cilium.io/ips: "10.1.1.60"
    spec:
      loadBalancerClass: io.cilium/l2-announcer
