traefik:
  providers:
    kubernetesGateway:
      enabled: true
    kubernetesIngress:
      enabled: false

  gateway:
    enabled: false

  service:
    spec:
      loadBalancerClass: io.cilium/l2-announcer
