apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
