apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:xmple/talos-cluster.git
        revision: main
        directories:
          - path: cluster/apps/*
          - path: cluster/apps/argocd
            exclude: true
  template:
    metadata:
      name: "{{ `{{.path.basename}}` }}"
    spec:
      project: cluster
      source:
        repoURL: git@github.com:xmple/talos-cluster.git
        targetRevision: main
        path: "{{ `{{.path.path}}` }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ `{{.path.basename}}` }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
