apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: db3000-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:xmple/talos-cluster.git
        revision: main
        files:
          - path: cluster/db3000/*/config.json
  template:
    metadata:
      name: "{{ `{{.appName}}` }}"
      labels:
        app-group: "{{ `{{.group}}` }}"
    spec:
      project: cluster
      source:
        repoURL: git@github.com:xmple/talos-cluster.git
        targetRevision: main
        path: "{{ `{{.chartPath}}` }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: db3000
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
