longhorn:
  defaultSettings:
    defaultReplicaCount: 1
    defaultDataPath: /var/lib/longhorn
    backupTarget: "s3://longhorn-backup@us-east-1/"
    backupTargetCredentialSecret: longhorn-s3-secret
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
