apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-share
  namespace: db3000
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: db3000-media-share
  resources:
    requests:
      storage: 100Gi
