hostname: pg.xmple.io

instances: 3

storage:
  size: 10Gi
  storageClass: longhorn-single-replica

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi

affinity:
  enablePodAntiAffinity: true
  topologyKey: kubernetes.io/hostname

initdb:
  database: app
  owner: app

managedRoles:
  - name: gitea
    createdb: true
  - name: authelia
  - name: teslamate
  - name: hass
  - name: jellyseerr
  - name: grafana
    createdb: true

backup:
  endpointURL: "https://s3.xmple.io:9000"
  destinationPath: "s3://cnpg-backup/"
  secretName: cnpg-s3-creds
  retentionPolicy: "7d"
  wal:
    compression: gzip
    maxParallel: 1
  data:
    compression: gzip
    jobs: 2

scheduledBackup:
  schedule: "0 0 0 * * *"
