gha-runner-scale-set:
  githubConfigUrl: "https://github.com/sociaei"
  githubConfigSecret: arc-github-app

  runnerScaleSetName: "arc-runner"

  minRunners: 1
  maxRunners: 5

  containerMode:
    type: "kubernetes"
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "longhorn-single-replica"
      resources:
        requests:
          storage: 1Gi

  controllerServiceAccount:
    namespace: arc-controller
    name: arc-controller-gha-rs-controller
