kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi

  prometheus:
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi

  grafana:
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: longhorn
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc:80
        access: proxy
        isDefault: false

  # etcd scraping — Talos exposes etcd metrics on port 2381
  kubeEtcd:
    enabled: true
    endpoints:
      - 10.1.1.140
      - 10.1.1.146
      - 10.1.1.203
    service:
      enabled: true
      port: 2381
      targetPort: 2381
