gha-runner-scale-set:
  githubConfigUrl: "https://github.com/sociaei"
  githubConfigSecret: github-arc-app

  runnerScaleSetName: "github-arc-runner"

  minRunners: 1
  maxRunners: 5

  containerMode:
    type: "kubernetes-novolume"

  template:
    spec:
      securityContext:
        fsGroup: 1001
      volumes:
        - name: work
          emptyDir: {}
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work

  controllerServiceAccount:
    namespace: github-arc-controller
    name: github-arc-controller-gha-rs-controller
