apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: migration
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://longhorn@us-east-1/"
  credentialSecret: longhorn-s3-secret
  pollInterval: 5m0s
