apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: monitoring
  annotations:
    lbipam.cilium.io/sharing-key: default
    lbipam.cilium.io/ips: "10.1.1.60"
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 1515
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 1515
      protocol: TCP
  selector:
    app.kubernetes.io/name: alloy
