apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 1515
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 1515
      protocol: TCP
    - name: apc-syslog
      port: 10514
      targetPort: 1516
      protocol: UDP
  selector:
    app.kubernetes.io/name: alloy
