repoURL: git@github.com:xmple/talos-cluster.git
targetRevision: main
project: cluster

autoSync: true

apps:
  - name: gitea
    namespace: gitea
    path: cluster/apps/gitea
  - name: gitea-runner
    namespace: gitea-runner
    path: cluster/apps/gitea-runner
    serverSideDiff: true
