repoURL: git@github.com:xmple/talos-cluster.git
targetRevision: main
project: cluster

autoSync: true

apps:
  - name: gitea
    namespace: gitea
    path: cluster/apps/gitea
  - name: gitea-runner
    namespace: gitea-runner
    path: cluster/apps/gitea-runner
    serverSideDiff: true
  - name: arc-controller
    namespace: arc-controller
    path: cluster/apps/arc-controller
  - name: arc-runner
    namespace: arc-runner
    path: cluster/apps/arc-runner
