media-app:
  image:
    repository: ghcr.io/advplyr/audiobookshelf
    tag: "2.34.0"
  containerPort: 80
  env:
    TZ: Europe/London
    CONFIG_PATH: /data/config
    METADATA_PATH: /data/metadata
    BACKUP_PATH: /data/backups
  persistence:
    config:
      size: 5Gi
      existingVolume: db3000-audiobookshelf-config
      mountPath: /data
    media:
      enabled: true
  httproute:
    path: /audiobookshelf
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 1Gi
