apiVersion: v1
kind: Secret
metadata:
  name: cnpg-server-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # ISRG Root X1 — Let's Encrypt root CA (valid until 2035-06-04)
  # https://letsencrypt.org/certs/isrgrootx1.pem
  ca.crt: {{ .Files.Get "files/isrgrootx1.pem" | b64enc | quote }}
