apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.instances }}

  storage:
    size: {{ .Values.storage.size }}
    storageClass: {{ .Values.storage.storageClass }}

  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  certificates:
    serverTLSSecret: cnpg-server-tls
    serverCASecret: cnpg-server-tls

  enableSuperuserAccess: true
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: {{ .Values.initdb.database }}
      owner: {{ .Values.initdb.owner }}

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-cluster-backup
