apiVersion: v1
kind: Service
metadata:
  name: cnpg-cluster-lb
  labels:
    app.kubernetes.io/name: cnpg-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: cnpg-cluster
  annotations:
    lbipam.cilium.io/ips: "10.1.1.62"
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: cnpg-cluster
    role: primary
