repoURL: git@github.com:xmple/talos-cluster.git
targetRevision: main
project: cluster

autoSync: true

apps:
  - name: cert-manager
    namespace: cert-manager
    path: cluster/apps/cert-manager
  - name: longhorn
    namespace: longhorn-system
    path: cluster/apps/longhorn
  - name: smb-csi
    namespace: smb-csi
    path: cluster/apps/smb-csi
  - name: renovate
    namespace: renovate
    path: cluster/apps/renovate
  - name: nfd
    namespace: nfd
    path: cluster/apps/nfd
  - name: intel-gpu
    namespace: intel-gpu
    path: cluster/apps/intel-gpu
  - name: cnpg-operator
    namespace: cnpg-system
    path: cluster/apps/cnpg-operator
  - name: barman-cloud-plugin
    namespace: cnpg-system
    path: cluster/apps/barman-cloud-plugin
