apiVersion: v1
kind: PersistentVolume
metadata:
  name: db3000-jellyfin-cache
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: db3000-jellyfin-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: longhorn
  volumeName: db3000-jellyfin-cache
  resources:
    requests:
      storage: 10Gi
