apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: db3000
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
